// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twejmhqbibellgduyxvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZWptaHFiaWJlbGxnZHV5eHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjgyNDIsImV4cCI6MjA2Njc0NDI0Mn0.5ApOrRmXeox-zU5hulgfRW_CHypUU7W74_nnV6nggnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);